### ISSUE TITLE
Facebook OG Meta Image Bug

### ISSUE THREAD

**Issue by g1powermac** [gnotaras/wordpress-add-meta-tags#21]
Hello,

There's a bug with the plugin under Wordpress when changing a featured image for the post.  When the featured image is changed, the original OG:Image tag isn't replaced with the new image link.  Instead, another OG:Image meta tag is created with the new image, showing multiple images including the old and incorrect one.

**Comment by gnotaras** [comment]
Hello, thanks for your report and I'm sorry for the late reply.

I'll try to investigate this asap and reply back at some later time today.

Some more info would be usefulI.. Is the featured image the only image attached to the post? If the old image is still attached to the post, then what happens is normal as AMT tries to add metadata for all attached images. This is by design and not an issue of the plugin.

If this is the case, you will have to browse to media library list view at `/wp-admin/upload.php` locate the old image and click `Detach` under the _Uploaded to _ column. This is really a WordPress thing (admittedly cumbersome) and I cannot do anything about it.

I'll reply back soon with more info.

Kind Regards,
George

**Comment by g1powermac** [comment]
Hi George,

I checked out the images, and yes they are still attached to the post.  That is definitely a bizarre feature from Wordpress, especially since one image I only uploaded and never set to use as the featured image. After detaching, it is working as it should.  Thank you for pointing this out!

**Comment by gnotaras** [comment]
Hi, really glad you have sorted this out and also glad it's not a bug!

I also thank you for pointing this out as a section in the FAQ about it needs to be added! :)

Kind Regards,
George
