### ISSUE TITLE
Problems sharing to Linkedin

### ISSUE THREAD

**Issue by gabrielwinnberg** [gnotaras/wordpress-add-meta-tags#23]
A client has problems sharing their content on Linkedin. I've carefully studied Linkedin's suggestions and to my knowledge I got everything right (https://developer.linkedin.com/docs/share-on-linkedin) using Add Meta Tags:

`<html prefix="og: http://ogp.me/ns#">`
`<head>`
`  <meta property="og:title" content="My Shared Article Title" />`
`  <meta property="og:description" content="Description of shared article" />`
`  <meta property="og:url" content="http://example.com/my_article.html" />`
`  <meta property="og:image" content="http://example.com/foo.jpg" />`
`</head>`

For the prefix in the html tag I had to manually edit the code. I've waited ten days or so for changes to take effect, and everything looks perfect in Facebook's testing tool (https://developers.facebook.com/tools/debug/og/object/) as well as when sharing on G+.

This is the URL I'm trying to share on Linkedin: http://www.c***.se

Any suggestions what might be the problem?

**Comment by gnotaras** [comment]
Hello Gabriel,

Thanks for your question.

Adding the Opengraph namespace in the prefix attribute of the `html` tag has been in my todo list since a long time ago and this is a good reminder to do some more research and see if the automatic addition resolves more problems than it creates.

Alternatively, instead of editing the theme templates, you could try the following code in the theme's `functions.php` (please note it does not work with all themes):

```php
function amt_add_og_xml_namespace( $content ) {
  return ' xmlns:og="http://ogp.me/ns#" ' . $content;
}
add_filter('language_attributes', 'amt_add_og_xml_namespace');
```
About *sharing on LinkedIn*, I've recently received feedback from another user experiencing the same issue. To save some typing I'll quote my reply:

```
Below are some pointers after a quick look at the page:

- Please make sure that the opengraph metadata validates properly in
Facebook's debug tool at https://developers.facebook.com/tools/debug/

- Ensure that the intended image meets possible special LinkedIn image
requirements. As far as image dimensions on LinkedIn are concerned I
think this is 150x80 pixels.

- If LinkedIn is accessed over HTTPS, it might be a good idea to also
make your media files available over HTTPS on your web site. As far as I
can tell your web site is currently _not_ accessible over HTTPS. In this
case, if the LinkedIn pages included the insecure URL to your image, the
web browser would warn the user about this issue and, possibly, LinkedIn
does not want that. So, this is a very possible point of failure.

- You could try to limit the generated 'og:image' meta tags to 1 by
checking the option that can be found in the settings page at:
Settings-> Metadata-> Media Limit

- Alternatively, you can force a specific image URL by:
  a) enabling the 'Global image override' setting in the settings page
at Settings-> Metadata-> Metabox features, and
  b) by specifying an image URL in the relevant field of the 'Metadata'
box in the post editing screen.

...

As a side note, whenever HTTPS access is enabled, it would be a good
idea to also enable the option at 'Settings-> Metadata-> Secure Access'.
If this is checked, the plugin and as far as Opengraph is concerned, in
addition to adding HTTP image URLs in 'og:image' meta tags, will also
generate 'og:image:secure_url' meta tags, even if the web page has been
requested over plain HTTP. The plugin doesn't do this automatically to
avoid making decisions on its own regarding HTTPS access because of the
various ways it can be set up.
```
The user replied that _without making any changes_, subsequent shares on LinkedIn started working fine. This tells me that there is no problem with the generated metadata. The Facebook debug tool also confirms that.

As for what could be the problem, I cannot really tell for sure. I'd say that media availability over HTTPS on your end should be implemented at some point to ensure that your media files can be link by pages that are served over HTTPS without any warnings on the user's browser.

About the missing namespace, I'd say it's a minor issue and should not be the real problem.

Perhaps, a question on a LinkedIn support channel could shed more light on this issue. Any feedback about incorrect metadata on the Add-Meta-Tags' end would be greatly appreciated, but so far I have no indication that this is the case.

Hope these help you!

I'm going to leave this issue open for a while for further discussion and feedback.

Best Regards,
George

**Comment by gnotaras** [comment]
@gabrielwinnberg Has there been any progress with this issue? Do you still encounter the issue when sharing on LinkedIn?

**Comment by gabrielwinnberg** [comment]
Hello George,

First a very big thank you for the great response.

Another client got in the way for a couple of weeks but I'll soon be back
on this issue. It is not solved yet.


Best regards,
Gabriel



Mobile: +46 733 56 64 45
Skype: gabrielwinnberg
http://gabrielwinnberg.com

2016-01-21 12:18 GMT+01:00 George Notaras <notifications@github.com>:

**Comment by gnotaras** [comment]
OK Gabriel, thanks for the update. Feedback is very welcome.

George

**Comment by gabrielwinnberg** [comment]
Hello George,

Thanks for the tip on changing namespace in *functions.php*.

Just a few comments. I'll dive more into this later on.

   - This is apparently a common problem.
   - It is perfectly validated using FB's debug tool.
   - I use Themeco's X Theme for a number of sites, quite heavily
   customized. All sites show Linkedin shares perfectly except this one (
   www.centigo.se).
   - They have the same web hotel as several other clients.
   - The site doesn't use any HTTPS (apart from wp-admin) so it shouldn't
   be an issue.
   - One guy claims he solved the problem using an even more elaborate
   namespace, which would seem strange to me:
   *<html xmlns:og="http://ogp.me/ns# <http://ogp.me/ns#>"
   xmlns:fb="http://ogp.me/ns/fb# <http://ogp.me/ns/fb#>"
   xmlns="http://www.w3.org/1999/xhtml <http://www.w3.org/1999/xhtml>"
   xmlns:og="http://opengraphprotocol.org/schema/
   <http://opengraphprotocol.org/schema/>"
   xmlns:fb="http://www.facebook.com/2008/fbml
   <http://www.facebook.com/2008/fbml>" lang="nl" >*
   - Haven't had chance to test it but authors of this plugin claim they
   fix it:
   https://wordpress.org/plugins/linkedin-perfect-share/
   - I can't quite get my head around which image size to use, different
   sources state different things. Here for example they say (
   https://help.linkedin.com/app/answers/detail/a_id/46687/ft/eng):
      - Max file size: 1 MB
      - Minimum image dimensions: 80 x 150 pixels
      - Recommended aspect ratio: 4:1 or 1:4
   - They also say "your website may be blocking us from pulling the image
   or the image may be located on a protected directory or website". Well it's
   not since it's accessible from other sites.
   - Other resources state completely other sizes as ideal.

I'll try the other stuff when I get a chance.

I'll write you soon again.


Cheers,
Gabriel


Mobile: +46 733 56 64 45
Skype: gabrielwinnberg
http://gabrielwinnberg.com

2016-01-22 2:54 GMT+01:00 George Notaras <notifications@github.com>:

**Comment by gnotaras** [comment]
Hi Gabriel,

Thanks for your reply.

>  - I use Themeco's X Theme for a number of sites, quite heavily customized. All sites show Linkedin shares perfectly except this one ( www.centigo.se).

Currently there are no opengraph meta tags on this particular web site, but I guess you might be working on it. Is there a web site using Add-Meta-Tags on which sharing to LinkedIn works as expected? I'm trying to figure out if the plugin is doing something wrong with the opengraph metadata, but I'm out of ideas about what the problem might be. As far as I can tell, the OG meta tags are generated according to the specs.. I'll keep looking into this.

> - The site doesn't use any HTTPS (apart from wp-admin) so it shouldn't be an issue.

This means that media files can be accessed over HTTPS and, since this is the case, then this should not be any problem. BTW, it would be a _good idea_ to enable the option at 'Settings-> Metadata-> Secure Access' in the AMT settings.

> - One guy claims he solved the problem using an even more elaborate namespace, [...]

Honestly, I doubt that the issue here is the namespace. The namespace would be important to a validator service and possibly only for a set of meta tags that are unknown or not so popular... I'd expect the LinkedIn indexer to be looking directly at OG meta tags without previously checking the existence of the relevant namespace inside a parent tag. Also, if the namespace was the issue, I'd expect the problem to happen with other pieces of OG metadata as well and not only with the images.

> - Haven't had chance to test it but authors of this plugin claim they fix it: https://wordpress.org/plugins/linkedin-perfect-share/

Thanks for letting me know! I'll take a closer look to see what exactly is being done by this plugin. But I really think the problem exists somewhere outside the metadata.

Taking a look `http://www.centigo.se/robots.txt` I see the following:

```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php

Sitemap: http://www.centigo.se/sitemap.xml
<!-- WP Super Cache is installed but broken. The path to wp-cache-phase1.php in wp-content/advanced-cache.php must be fixed! -->
```

What puzzles me is whether the `Allow: /wp-admin/admin-ajax.php` statement could be interpreted as *only allow this* by the indexers. On the other hand the page content seems to have been indexed by Google. Maybe you should take a closer look at robots.txt and make sure that indexers are allowed to access all directories. I think this is important.

>  - I can't quite get my head around which image size to use, different sources state different things. Here for example they say ( https://help.linkedin.com/app/answers/detail/a_id/46687/ft/eng): - Max file size: 1 MB - Minimum image dimensions: 80 x 150 pixels - Recommended aspect ratio: 4:1 or 1:4 > - They also say "your website may be blocking us from pulling the image or the image may be located on a protected directory or website". Well it's not since it's accessible from other sites.
> - Other resources state completely other sizes as ideal.

Yeah, I'm puzzled as well. I've done some research about it and I've found various pieces of information and workarounds. But all of them are just based on 'trial and error'. Have you tried asking in any LinkedIn support channel about this (if this is possible at all)? They should be able to point out what the problems might be in such cases and possibly guide you to the right direction.

Any information about this issue is very welcome and much appreciated.

Kind Regards,
George

**Comment by gabrielwinnberg** [comment]
Hi,


> Currently there are no opengraph meta tags on this particular web site,
> but I guess you might be working on it. Is there a web site using
> Add-Meta-Tags on which sharing to LinkedIn works as expected? I'm trying to
> figure out if the plugin is doing something wrong with the opengraph
> metadata, but I'm out of ideas about what the problem might be. As far as I
> can tell, the OG meta tags are generated according to the specs.. I'll keep
> looking into this.



What do you mean "are no opengraph meta tags on this particular web site"?
They show up using FB's debug tool, or am I missing something?

This means that media files can be accessed over HTTPS and, since this is
> the case, then this should not be any problem. BTW, it would be a good idea
> to enable the option at 'Settings-> Metadata-> Secure Access' in the AMT
> settings.


Thanks for the explanation, I switched it on.

Honestly, I doubt that the issue here is the namespace. The namespace would
> be important to a validator service and possibly only for a set of meta
> tags that are unknown or not so popular... I'd expect the LinkedIn indexer
> to be looking directly at OG meta tags without previously checking the
> existence of the relevant namespace inside a parent tag. Also, if the
> namespace was the issue, I'd expect the problem to happen with other pieces
> of OG metadata as well and not only with the images.



But all metadata are missed, nothing comes up when I try it on LinkedIn. Do
you get a different result?


>  Taking a look http://www.centigo.se/robots.txt I see the following:
>

> Disallow: /wp-admin/
> Allow: /wp-admin/admin-ajax.php
>
> 
>

User-agent: *
>
Sitemap: http://www.centigo.se/sitemap.xml
>


What puzzles me is whether the Allow: /wp-admin/admin-ajax.php statement
> could be interpreted as *only allow this* by the indexers. On the other
> hand the page content seems to have been indexed by Google. Maybe you
> should take a closer look at robots.txt and make sure that indexers are
> allowed to access all directories. I think this is important.



Interesting. When comparing to another site that works (
www.accuratenordic.com) Centigo has installed the plugin *XML Sitemap
Generator for WordPress 4.0.8* which produces the sitemap link. Could there
be a conflict?

http://www.accuratenordic.com/robots.txt:

User-agent: *

Disallow: /wp-admin/

Allow: /wp-admin/admin-ajax.php


http://ng.kramgo.se/robots.txt:

User-agent: *

Disallow: /


When testing different sites I've worked on I now see some differences. The
following are shared properly:

http://www.accuratenordic.com
http://ng.kramgo.se – under development


The following are not shared properly (haven't checked OG tags to be
honest, too limited budgets):

http://www.centigo.se – nothing

http://gatereport.com – nothing
http://www.johanstrom.com – lacks image


Yeah, I'm puzzled as well. I've done some research about it and I've found
> various pieces of information and workarounds. But all of them are just
> based on 'trial and error'. Have you tried asking in any LinkedIn support
> channel about this (if this is possible at all)? They should be able to
> point out what the problems might be in such cases and possibly guide you
> to the right direction.


I have not yet posted anything but I'll do that. However numerous other
people have posted about the same thing.


Regards,
Gabriel


Mobile: +46 733 56 64 45
Skype: gabrielwinnberg
http://gabrielwinnberg.com

2016-01-30 0:47 GMT+01:00 George Notaras <notifications@github.com>:

**Comment by gnotaras** [comment]
Hi Gabriel,

> What do you mean "are no opengraph meta tags on this particular web site"? They show up using FB's debug tool, or am I missing something?

Yep, everything is in tact. I must had checked an archive or the homepage. I'm sorry about that! :)

I'll go through the rest of your message at some later time.

George

**Comment by gnotaras** [comment]
Gabriel, you did very well to post those links so as to be able to check them, but I had to remove them afterwards in order to avoid misunderstandings with other users, because I usually moderate the issues that contain more than 1 links. I hope you understand and there is no problem with that. :)

The findings according to my tests are exactly as you described. However, in those sites for which sharing on LinkedIn did not work I noticed issues with viewing the page in my browser (gatereport), images that are not attached to posts (but possibly added as `img` tags inside the post) so AMT does not generate metadata for them (eg johanstrom/talk/ ), or possible issues with the robots.txt file.

Regarding robots.txt, the following should not be a problem. The web site should be indexed normally and it actually is.

```
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php
```

But this should probably be fixed (in centigo robots.txt):

```
<!-- WP Super Cache is installed but broken. The path to wp-cache-phase1.php in wp-content/advanced-cache.php must be fixed! -->
```

Sharing from accuratenordic and kramgo worked fine.

I also did some testing with other web sites and sharing the link produced the preview properly with its image without problems. So, I tend to believe that the issue exists outside the metadata. And I would highly recommend contacting a LinkedIn support channel for more information about what might be wrong.

I'm afraid there is nothing more I can do about this issue. I'll keep it open for a little longer. Please feel free to add more information in case LinkedIn support sheds some light to the problem.

Kind Regards,
George

**Comment by gnotaras** [comment]
Also, the sitemap URL inside the robots.txt as added by the sitemaps plugin is perfectly valid and should not be a problem.

**Comment by gabrielwinnberg** [comment]
> Gabriel, you did very well to post those links so as to be able to check them, but I had to remove them afterwards in order to avoid misunderstandings with other users, because I usually moderate the issues that contain more than 1 links. I hope you understand and there is no problem with that. :)

Thanks, I actually forgot that this is a public forum since I responded to mail. Better this way.

> But this should probably be fixed (in c*** robots.txt): `<!-- WP Super Cache is installed but broken. The path to wp-cache-phase1.php in wp-content/advanced-cache.php must be fixed! -->`

Thanks for pointing that out. It turns out to be a remnant, Super Cacha has been deinstalled. Evidently, when they migrated the site to it's live location they hadn't removed it properly. In `wp-config.php` there was still `define('WP_CACHE', true);` which in turn called `advanced-cache.php` which pointed to the non-existant plugin. When I comment out  `define('WP_CACHE', true);` the line disappears, so `robots.txt`is now:

```
User-agent: *
Disallow: /wp-admin/
Allow: /wp-admin/admin-ajax.php

Sitemap: http://www.c***.se/sitemap.xml
```

I'll be back when I have more on your suggestions. Thanks for keeping the thread open.

**Comment by gnotaras** [comment]
Gabriel,

I replied via email, but I'm also posting this here for other users.

I performed the following request using LinkedIn bot's user agent string to an image of the aforementioned web site and the request is forbidden by the server.

Here is the output:

```
$ curl -I -L -A "LinkedInBot/1.0 (compatible; Mozilla/5.0; Jakarta Commons-HttpClient/3.1 +http://www.linkedin.com)" http://www.c************/wp-content/uploads/2016/01/c********.jpg
HTTP/1.1 403 Forbidden
Date: Sat, 30 Jan 2016 15:16:29 GMT
Server: Apache/****
Content-Type: text/html; charset=iso-8859-1
```

So this is a server issue (htaccess) or an issue with a security plugin blocking access.

George

**Comment by gabrielwinnberg** [comment]
Yes, this could be a cause. When I access the site using HTTPS it won't load the logo. HTML reveals:

`<img src="//c***.se/wp-content/uploads/2015/11/logo_03_retina.png" alt="xxx">`

Compare with A's site that works I find that www is gone:

`<img src="//www.a***.com/wp-content/uploads/2015/10/logo.png" alt="xxx">`

C*** is set to work at `www.c***.se` so I'm thinking there could be some paths left in the DB that refer to URLs without `www`. Again something left from the migration. This function generates the image path:

```
	$site_name        = get_bloginfo( 'name' );
	$logo             = x_make_protocol_relative( x_get_option( 'x_logo' ) );
	$site_logo        = '<img src="' . $logo . '" alt="' . $site_description . '">';

	<?php echo ( $logo == '' ) ? $site_name : $site_logo; ?>
```

When accessing the image directly I first have to accept the certificate:

`https://c***.se/wp-content/uploads/2015/11/logo_03_retina.png`

The certificate is issued for the Hosting company `*.l***.com` so an error is generated. Also, when trying to access the image in Safari without www it takes a long time before it resolves it. At the same time `www.a***.com` is not accessible via HTTP, or rather there is nothing there.

Definitely something fishy here …

**Comment by gabrielwinnberg** [comment]
Solved … or partly solved!

It turns out to be remnants of the plugin **All In One WP Security & Firewall**. The firewall sets what's called 5G rules in .htaccess that simply blocks requests from LinkedIn because they have the word `jakarta` in their request string as you show above.

The plugin uses an outdated version of the blacklist, the "5th generation":

```
# BEGIN All In One WP Security
#AIOWPS_FIVE_G_BLACKLIST_START
# 5G BLACKLIST/FIREWALL (2013)
# @ http://perishablepress.com/5g-blacklist-2013/
```

of which they now say:

> Update (2015/04/03): removed jakarta from the user-agent portion of the list. Reason? LinkedIn actually includes the term “jakarta” in their user-agent string:
> 
> LinkedInBot/1.0 (compatible; Mozilla/5.0; **Jakarta** Commons-HttpClient/3.1 +http://www.linkedin.com)

The image is still not displayed correctly, which could be an HTTPS issue or something related to the shorter URL used for the image `http://c***.se` instead of `http://www.c***.se`.

**Comment by gnotaras** [comment]
Since the discussion had been going on via email too, here is an update for the readers of this ticket. It seems that after removing the old security rules from htaccess that blocked LinkedIn's bot, sharing on LinkedIn has started working again.

Regardless of this resolution, I'll consider adding an option that adds the opengraph namespace. According to my tests, the missing namespace should not cause any problems, but it will be added for completeness. So, I'll also mark the issue as _enhancement_ and keep it open until this is implemented.

Gabriel, thanks for all your feedback! Much appreciated!

George

**Comment by gnotaras** [comment]
Hello Gabriel,

An option that adds Facebook's XML namespaces has been added in 2.10.8.

If you have used the above snippet in any of your web sites, please **remove it before updating to 2.10.8** to avoid a PHP error of duplicate functions.

I'll now close this issue. Thanks for your feedback!

George

**Comment by gabrielwinnberg** [comment]
Many thanks!

Cheers,
Gabriel

Mobile: +46 733 56 64 45
Skype: gabrielwinnberg
http://gabrielwinnberg.com

2016-02-04 18:03 GMT+01:00 George Notaras <notifications@github.com>:
