### ISSUE TITLE
Express review box coverting URL special characters

### ISSUE THREAD

**Issue by Tharic-Nar** [gnotaras/wordpress-add-meta-tags#28]
Fantastic plugin, have been using it for a while and only beginning to scratch the surface of what it's capable of. Our site started to test out the express review box to add schema code for certain articles, to provide an SEO friendly rating. This normally requires a URL to be provided. However, certain URLs with parameters are parsed to have their special characters converted into HTML friendly strings: for example, the ampersand & is converted into &amp which breaks the URL (or causes it to clip the rest of the URL).

With some testing, converting the character into URL percent code (& becomes %26 I believe) doesn't work either for certain URLs. To give you some idea, this is the URL we wish to set:

http://www.inwin-style.com/en/goods.php?act=view&id=D-Frame%20mini

When set in express review, it gets converted to:

http://www.inwin-style.com/en/goods.php?act=view&amp

Changing the URL to the following, links to the wrong page, since it requires the & as a symbol and not as a text character:

http://www.inwin-style.com/en/goods.php?act=view%26id=D-Frame%20mini

Would it be fair to disable text parsing in the express review box (and possibly the other advanced meta boxes), or is it required for the plugin to work correctly?

Many thanks, and great work with this plugin.

**Comment by gnotaras** [comment]
Hello and thanks for your feedback and the kind words!

I see. I'll try to take a closer look at it as soon as I get some spare time. The example URL is going to be very helpful for my tests. Thanks.

> Would it be fair to disable text parsing in the express review box (and possibly the other advanced meta boxes), or is it required for the plugin to work correctly?

It would definitely make the plugin less secure, but in this particular case this is a legit piece of text and should not be converted. I'll see what can be done and I'll keep you updated.

Kind Regards,
George

**Comment by Tharic-Nar** [comment]
OK, this might help - I haven't checked the code you use, but it's acting like the input fields use **sanitize_text_field()** to sanitize - this will likely treat the url as a text string and thus convert symbols into html entities.

An alternative might be to use **wp_kses()** or the pre-defined array **wp_kses_post()** or **wp_kses_data()**, as it allows a whitelist of html elements and protocols. It should sanitizing the text, but I don't know if it'll leave the url alone (it should do, as long as it's a full URL with http:// or https://):

http://codex.wordpress.org/Function_Reference/wp_kses

Would this break your plugin though, since you use your own formatting on the submitted text field? It does mean that users might be able to insert their own html accidentally into the field, so I'm not sure if this is a valid option unless you use a very strict whitelist array.

Thanks for looking into this, and keep up the very excellent work.

**Comment by gnotaras** [comment]
Hi, I took a look at it yesterday. It actually passes the review information through `esc_textarea( wp_kses( ... ) )` for security reasons. Apart from the conversion to the HTML entity `&amp;`, the real problem in this case was because the review information is parsed as INI data by `parse_ini_string()`, in which `;` is treated as a comment character, which resulted in cutting the URL at `&amp`. I fixed it yesterday, but haven't pushed the change yet as I wanted to test it a bit more.

The fix is to revert the sanitization of `&` to `&amp;` and revert it back to `&`. As far as I can tell it does not impose any security risks.

I'll let you know when I push the changeset, so you can apply the change yourself if you like, before the new AMT release is out.

George

**Comment by Tharic-Nar** [comment]
Thank you very much for looking into this and the quick fix, much appreciated. Release whenever you think it's ready, I'm not in any rush since that's the only URL (or indeed, issue at all), I've had with AMT so far. Thanks again.

**Comment by gnotaras** [comment]
Hi Tharic, I'll make a new release which contains the fix. Please let me know if the problem is resolved. I've also added some tasks to update the wiki about the Express review feature.

As a quick note, when this is enabled, the Schema.org microdata generator also adds a small piece of text containing information about the review. This is based on an internal template:

```
<div id="review-info" class="review-info">
    <p>This is a review of
    <span itemprop="itemReviewed" itemscope itemtype="http://schema.org/#object#">
        <a title="#object#: #name#" href="#sameAs#" itemprop="sameAs"><span itemprop="name">#name#</span></a>
#extra#
    </span>, which has been rated with 
    <span class="rating" itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
        <span itemprop="ratingValue">#ratingValue#</span>/<span itemprop="bestRating">#bestrating#</span>
    </span> stars!</p>
</div>
```

This template can be changed by attaching a filtering function to the `amt_schemaorg_review_info_template` hook:

```php
function amt_my_custom_review_info_template( $default ) {
    // Template variables: #ratingValue#, #bestrating#, #object#, #name#, #sameAs#, #extra#
    // #extra# contains meta elements containing the extra properties of the reviewed item.
    return $my_template_string;
}
add_filter('amt_schemaorg_review_info_template', 'amt_my_custom_review_info_template');
```

Alternatively, if you need to filter the output after the template has been processed, use the `amt_schemaorg_review_info_output` filter hook instead.

I'll make sure I update the wiki with more information about this feature very soon.

I'll now close this issue. Please feel free to add more info or open a new one.

Best Regards,
George
