### ISSUE TITLE
Use custom fields in full meta tags

### ISSUE THREAD

**Issue by philayres** [gnotaras/wordpress-add-meta-tags#3]
To start with, let me say thanks for the great plugin. I've just started using it and wanted to make an addition. Before I go to the effort of a pull request, I'd like to see if you'd be interested in it.

The aim is to provide dynamic replacement of certain delimited strings in the post full meta tags with equivalently name custom fields defined in the post.

For example:

    <meta name="geo.position" content="[Latitude];[Longitude]" />
    <meta name="ICBM" content="[Latitude], [Longitude]" />
    <meta name="geo.region" content="[Country]-[Regioncode]" />
    <meta name="geo.placename" content="[Placename]" />

Would replace the square bracketed Latitude, Longitude etc with the equivalent custom fields values from the post. From a user perspective this is a little more friendly and can provide flexibility to use the data for other purposes without having to copy and paste.

The code is actually simple:

    <?php
    function amt_sub_post_fields($post_id, $text){
        preg_match_all("/\[[^\]]*\]/", $text, $matches);

        foreach($matches[0] as $ma){
            $m=$ma;
            $mt = substr($m,1,-1);
            $mv= get_post_meta($post_id, $mt, true);
            $text = str_replace($m, $mv, $text);
        }
        return $text;
    }
    ?>

I'm calling it in amt_basic.php at about line 232:

        $full_metatags_for_content = amt_get_post_meta_full_metatags( $post->ID );
        if ( ! empty( $full_metatags_for_content ) ) {
            // the new call is here
            $full_metatags_for_content=amt_sub_post_fields($post->ID, $full_metatags_for_content);
            $metadata_arr[] = html_entity_decode( stripslashes( $full_metatags_for_content ) );
        }

And that is it. If you need a pull request, I'll do it next time I get to my pc (I'm on a tablet right now). Or feel free to incorporate it appropriately yourself.

Shout if you have questions.

**Comment by gnotaras** [comment]
Hello @philayres ,

Actually, this is a great piece of functionality as it facilitates the customization of the meta tags via other Custom Fields. I'd be happy to receive a pull request at any time.

However, I'm a bit hesitant to let the substitutions happen automatically as it could possibly lead to unexpected results for some users. It might be a good idea to let the user enable it via a filter (at least for now) so that the user is aware of what is going on.

Also, I had in my plans to let some pre-processing of the post's full meta tags and the site-wide ones take place. I intended to use the filter hook names `amt_full_metatags_post` and `amt_full_metatags_site` respectively.

So, this particular part of `amt_basic.php` (related to the post's full meta tags) could be:

```php
    $full_metatags_for_content = amt_get_post_meta_full_metatags( $post->ID );
    $full_metatags_for_content = apply_filters('amt_full_metatags_post', $full_metatags_for_content);
    if ( ! empty( $full_metatags_for_content ) ) {
        if ( apply_filters('amt_full_metatags_post_enable_field_substitutions', false) ) {
            // the new call is here
            $full_metatags_for_content=amt_sub_post_fields($post->ID, $full_metatags_for_content);
        }
        $metadata_arr[] = html_entity_decode( stripslashes( $full_metatags_for_content ) );
    }
```

To enable the substitutions, the following code would be required in the `functions.php` file of the theme or in a [custom plugin](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Cookbook_Snippet_Uses#Custom-Plugin):

```php
add_filter('amt_full_metatags_post_enable_field_substitutions', '__return_true');
```

Your feedback is welcome.

**Comment by philayres** [comment]
I understand your concerns regarding unexpected results for existing users.
Rather than another filter, how about a more complex (less likely to
accidentally use) format for the substitution tags? For example

    [[post_field:tag name]]

This might balance the need for lead technical users to have to edit php,
with more complex formatting of meta html.

As a third option I suppose we could also demand a post field with a
predefined name to be present, using it as a flag to enable the
functionality.

I'm willing to work either way, so let me know your preference and I'll
work up a commit.

**Comment by gnotaras** [comment]
> [...] how about a more complex [...]

Good ideas in order to get rid of that extra filter hook. But I think `[[post_field:tag name]]` becomes a little inconvenient for the editor.

How about using just the double brackets around the Custom Field name, eg `[[Country]]`, or adding a constant prefix that indicates that a Custom Field name is used inside the brackets, eg `[field:Country]`?

**Comment by gnotaras** [comment]
Phil, if you like any of the above suggestions, please feel free to go ahead with the one that you think is the most convenient for the editor. I think they are both complex enough to avoid any incidents of unwanted substitutions.

Thank you for your feedback.

**Comment by philayres** [comment]
I like the latter as it will be hard for anybody to claim they were using
that format already in their meta tags.

Also, should we replace unmatched field strings with blank, or leave them
unchanged? If we have a more complex substitution format I vote for blank.
For the simpler format I think we should leave unmatched fields unchanged.

Any preferences?

**Comment by gnotaras** [comment]
I vote for blank as well, since the special notation is always meant to be replaced by the field contents. Maybe there are cases that a blank value is what is expected (just wild guessing here).

**Comment by philayres** [comment]
I'm tied up in a production launch at work tomorrow, so I'll try to take a
shot at this later in the week. Fingers crossed...

**Comment by gnotaras** [comment]
Phil, please take your time and send a pull request whenever you have the time. If this is not possible due to other obligations, I can always incorporate the changes myself. FYI, time permitting, I plan to make a new release next week.

**Comment by gnotaras** [comment]
Hi, I didn't have the time to work on this enhancement for the 2.9.5 release. It's going to be implemented in 2.9.6.

**Comment by philayres** [comment]
George, thanks for staying on top of this. Unfortunately I've not had a
chance to look at it since we started this discussion a month ago. If I get
a few moments this week I will try again.

**Comment by gnotaras** [comment]
Hi Phil, I'm going to incorporate the changes we talk about in one of the next releases. I'm sorry for all this delay, but I needed to implement a lot of things lately and the time to work on this feature was literally non existent.

My plan is to 1) incorporate the changes with a new improved regex pattern, 2) test it with simple Custom Fields and also with the ACF plugin (advanced custom fields), and finally release it at some point during the next week or the week after that.

Again, I'm sorry for the delay,
George

**Comment by gnotaras** [comment]
@philayres 

Hello Phil,

I'm really sorry for the huge delay. Had to make some changes to the functionality of the full meta tags boxes before implementing field substitutions. And before that, some other features had priority as they had been planned since a long time ago.

I've implemented the feature as we discussed above with the difference that the special notation is like this:

```
[field=Field Name]
```

The rules are the following:

 * `Field Name` is the name of the custom field.
 * If the custom field with name `Field Name` does not exist, the meta tag that contains the special notation about is omitted. I thin this is better to omit the full meta tag than keeping an invalid value.
 * If the value of the field is an empty string, then the substitution still takes place normally. This is to cover cases that the value of the field is only part of the content of the meta tag.

This functionality will be available in 2.10.6.

Your comments are very welcome.

George

**Comment by philayres** [comment]
George, this looks like a great solution. I can't think of any reason why
it shouldn't work well in practice. I'll try it out some time over the next
week and get back to you.

Thanks!

**Comment by gnotaras** [comment]
Phil thanks for the fast reply. The feature is now final. I had to change `[field:Field Name]` to `[field=Field Name]`, because the `field:` part, if used in an `href` attribute of a `link` element inside the full meta tags boxes, was interpreted as an invalid protocol by a WP built-in sanitization function I use and it stripped it. Instead of adding custom sanitization, I preferred to change the notation.

Thanks for all your ideas and feedback.

I'll now close this issue.

George
