### ISSUE TITLE
Adding "full meta text" to template header

### ISSUE THREAD

**Issue by kylecgr** [gnotaras/wordpress-add-meta-tags#39]
I'm not very familiar with PHP, so I apologize for the seemingly simple question.

I used the "full meta tags" box on several pages to define the hreflang attribute. I'm using another SEO plugin to manage Titles / Breadcrumbs / Meta Descriptions.

I need a line of code that I can place in the header.php file of my Wordpress template to pull only the text that I have defined in the "full meta tags" box on each individual page.

Thanks in advance for your help.
Kyle

**Comment by gnotaras** [comment]
Hi, I'm sorry for the late reply.

The meta tags you enter in the 'Full meta tags' box should be displayed in the head section of the HTML source without any extra required manual action. They should be there, even if all metadata generators have been deactivated in the plugin settings (Settings->Metadata in the WP admin). I'm out of ideas about why this might not be happening.

I'd appreciate some more feedback about it. What options are enabled in the Add-meta-tags settings? What version of the plugin are you using? If you deactivate the other plugin, does the hreflang attribute show up?

Apart from this, the full meta tags are stored in a regular Custom Field with name: `_amt_full_metatags`. You can use the WordPress API to read data from Custom Fields. If you need more help with this, please let me know so I can provide sample code.

However, I recommend against using the full meta tags as is from the field, because the plugin does some more processing on them.

Please let me know if you need any help.

George

**Comment by gnotaras** [comment]
Hi, I'm going to close this issue. Please feel free to reopen it if needed or add more feedback.

George
