### ISSUE TITLE
Meta tags does not show after some time

### ISSUE THREAD

**Issue by swstarone** [gnotaras/wordpress-add-meta-tags#44]
Dear sir, I am using this Plugin in my BBpress forum, and I have noticed that meta tags shows when I recently save all settings but after some time all tags disappears and when I made a click on update/save setting then tags appears once again.
I also noticed that tags disappears from all over website including bbpress.
I need solution for this issue.

**Comment by gnotaras** [comment]
Hi,

Thanks for your feedback, but this issue does not seem to be related to the plugin, because there is no code that could possibly reset the options. Nevertheless, I'll try to look into this and reply back. Could you please check if you use any other plugins that could possibly affect WordPress options?

By the way, _bbPress_ metadata is still work in progress. Please keep the relevant setting *unchecked* in the plugin settings (section: _Extended Metadata_) for now. By checking it, no bbPress metadata is generated at the moment. By keeping it unchecked the bbPress topics areated as posts and generic metadata is added by the plugin.

Kind Regards,
George

**Comment by gnotaras** [comment]
I'm mentioning the general bbPress discussion topic ( #12 ) here, so that a reference is also created there.

**Comment by gnotaras** [comment]
Hi there, I'm going to close this issue as I cannot replicate in any way. Please feel free to add more feedback and reopen it if necessary.

Kind Regards,
George
