### ISSUE TITLE
WooCommerce: Editing title of shop page

### ISSUE THREAD

**Issue by its-thomas** [gnotaras/wordpress-add-meta-tags#47]
Hi George,

since there is another WooCommerce related post open here, I figured I'd post this one:

With my Twenty Eleven theme, the title of the WooCommerce shop page cannot be changed via your plugin - it always stays "Products | 'Site Name'".

The following fix for this issue works for me via editing of functions.php, but gives me WooCommerce-related PHP errors in the backend: https://support.woothemes.com/hc/en-us/articles/203739025-Change-WooCommerce-shop-page-title

Maybe you could look into this issue, so I can use your plugin to change the title here?

Greetings & Many Thanks in advance!

Thomas

**Comment by gnotaras** [comment]
Hi Thomas,

I'll look into this and try to fix any issues for the upcoming 2.10.10.

I also just received a reply from the WooCommerce devs about how the main shop page works. Even if it is set as a static front page, it still behaves as a custom post type archive. And this is possibly what my plugin does not currently take into account. It treats all pages set as the front page as regular post objects.

I'll reply back with more info as soon as I check this more closely.

Thanks for your feedback.

George

**Comment by gnotaras** [comment]
@its-thomas I made a small modification and I think both this issue and #46 are resolved.

Thanks for your feedback.

**Comment by its-thomas** [comment]
No, Thank YOU, George!
Looking forward to 2.10.10. :-)

**Comment by gnotaras** [comment]
Hi Thomas,

The problem with the title of the WC main shop page is a little complicated, so I'm going to outline my findings about how it behaves so that we both know what is possible and what is not. I'll also use this info for future reference.

First of all, I tested the code from the [WC support page](https://support.woothemes.com/hc/en-us/articles/203739025-Change-WooCommerce-shop-page-title) with the TwentyEleven theme and it seems to be working without any PHP notices or errors in my test environment. I used the following:

```php
function wc_custom_shop_archive_title( $title ) {
    if ( is_shop() ) {
        return str_replace( __( 'Products', 'woocommerce' ), 'My title', $title );
    }

    return $title;
}
add_filter( 'wp_title', 'wc_custom_shop_archive_title' );
```

In Add-Meta-Tags, changing the title of a **post/page/attachment/custom-post-type** object is possible in two ways:

 1. by setting a custom title in _Metadata_ metabox in the post edit screen.
 1. by enabling the _Advanced Title Management_ feature in the plugin settings and changing the [title templates](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Advanced_Title_Management) via a code snippet in `functions.php`.

Changing the titles of **archives** in AMT is **only** possible via:

 1. the _Advanced Title Management_ feature.

The special thing about WooCommerce's `shop` page is that, despite it being a WordPress static Page, it actually behaves like a _Custom Post Type Archive_. The page does not pass the `is_singular()` test (by WooCommerce design), so, changing its title using AMT is *only* possible via changing the title templates. The plugin would require several modifications in order to be able to use the page's custom title while it fails the `is_singular()` or `is_page()` tests.

However, if the WC `shop` page is set as the **static front page** in the WP settings (and only in that case), in AMT v2.10.10 it will be possible to also change the title by setting a custom title in the post edit screen. This is possible because in case of the front page AMT uses some other tests in addition to `is_singular()`.

If the **Advanced Title Management** feature is enabled in the AMT settings, then changing the title of the shop page when it is set as the **front page** is possible with the following snippets:

```php
// Templates for the 'title' element
function amt_custom_title_element_for_wc_shop($templates) {
    $templates['front_page_static']        = 'My Shop Front Page #entity_title# | #site_name#';
    $templates['front_page_static_paged']  = 'My Shop Main Archive | Page #page# | #site_name#';
    return $templates;
}
add_filter('amt_titles_title_element_templates', 'amt_custom_title_element_for_wc_shop');

function amt_custom_metadata_titles_for_wc_shop($templates) {
    $templates['front_page_static']        = 'My Shop Front Page | #site_name#';
    $templates['front_page_static_paged']  = 'My Shop Main Archive | Page #page# | #site_name#';
    return $templates;
}
add_filter('amt_titles_metadata_title_templates', 'amt_custom_metadata_titles_for_wc_shop');
```
On the contrary, if the `shop` page is **not** set as the front page, then it is possible to change the title templates for the _product_ custom post type archive:

```php
// Templates for the 'title' element
function amt_custom_title_element_for_wc_shop($templates) {
    // Custom Post Type Archives
    $templates['archive_posttype_product']        = 'My Shop Page | #site_name#';
    $templates['archive_posttype_product_paged']  = 'My Shop Main Archive | Page #page# | #site_name#';
    return $templates;
}
add_filter('amt_titles_title_element_templates', 'amt_custom_title_element_for_wc_shop');

function amt_custom_metadata_titles_for_wc_shop($templates) {
    // Custom Post Type Archives
    $templates['archive_posttype_product']        = 'My Shop Page | #site_name#';
    $templates['archive_posttype_product_paged']  = 'My Shop Main Archive | Page #page# | #site_name#';
    return $templates;
}
add_filter('amt_titles_metadata_title_templates', 'amt_custom_metadata_titles_for_wc_shop');
```

Unfortunately, there is nothing more I can do for this issue. If I think of another workaround I'll let you know.

George

**Comment by gnotaras** [comment]
Also, I edited the code snippet found on the WooCommerce support page so that it supports themes with the `title-tag` enabled as a theme feature instead of using the `wp_title()` template tag in the `header.php` template. Here is a more complete version:

```php
function wc_custom_shop_archive_title_alt($title) {

    if ( is_shop() ) {

        if ( is_array($title) ) {
            // WP >= 4.4
            $title['title'] = 'My title';
        } else {
            // WP < 4.4
            $title = str_replace( __( 'Products', 'woocommerce' ), 'My title', $title );
        }

    }

    return $title;
}
add_filter('document_title_parts', 'wc_custom_shop_archive_title_alt', 9999, 1);
add_filter('wp_title', 'wc_custom_shop_archive_title_alt', 9999, 1);
```
I use something similar in AMT.

George

**Comment by gnotaras** [comment]
Thomas, I'll now close this issue. Please feel free to reopen it if needed or add more feedback.

George

**Comment by its-thomas** [comment]
George, thanks so much for explaining the situation. It seems to me my best option is to use the code snippet.
I'll have to admit, I am still running Woocommerce 2.4.12 (and WP 4.3.1 for that matter) for the fear of running out of RAM on my webserver, which is already using 86% memory in the WP dashboard. But I suppose, I should at least update WooCommerce so the snippet will (should / might...) work without the PHP error...

Again, thanks so much for everything you did!

Thomas

PS: As soon as I am brave enough to update WooCommerce (maybe tonight ... ;-) ), I'll get back with a short status update.

**Comment by gnotaras** [comment]
You are welcome! Please take your time and feel free to add more information to this issue or open a new one whenever you test it. Thanks again for your feedback. :-)

**Comment by gnotaras** [comment]
Hi Thomas,

As far as I can tell, the `is_shop()` function is a WooCommerce conditional tag, so, if Woocommerce is activated, this error message seems a little strange.

I tried putting the above code in the `functions.php` file of the TwentyEleven and TwentySixteen themes and also in a custom plugin and it worked every time without issues.

Maybe this has to do with the child theme you might be using.

George

**Comment by its-thomas** [comment]
Oh, silly me!
I had Woocommerce loaded only on a handful of pages (using "Plugin Organizer" plugin) while putting the code snippet in the regular functions.php ...
I now have the code snippet in a custom plugin.php which is loaded on the same pages as Woocommerce - works like a charm.

2.10.10. is also installed and - oh - thanks for the shout-out ;-)

**Comment by gnotaras** [comment]
You are welcome! I see. Glad it works fine. BTW, the _Plugin Organizer_ plugin looks very interesting!

**Comment by its-thomas** [comment]
George,

_Plugin Organizer_ really is worth checking out!

Getting back to WooCommerce: Your plugin not being able to generate optimal metadata for the main WooCommerce products page (at the moment!) is a known issue, did I understand that correctly? I did however activate the WooCommerce option in your plugin's settings.

**Comment by gnotaras** [comment]
> Plugin Organizer really is worth checking out!

Will definitely do. Seems great!

> Your plugin not being able to generate optimal metadata for the main WooCommerce products page (at the moment!) is a known issue, did I understand that correctly?

Yes, this a known issue at the moment.. The WooCommerce shop page actually behaves like an archive of a custom post type (product), but is still mapped to a WordPress Page.

Before being able to generate proper metadata for the Page to which the product archive has been mapped, AMT needs to:

 1. detect this special Page
 1. access the post object of this special Page

But, by WooCommerce design:

 * the post object that is returned by `get_queried_object()`, when the 'shop' page is visited, is not the expected `WP_Post` object, but another custom one without any useful information for AMT and, also, without any indication (eg post ID) about the Page the archive has been mapped to.
 * the 'shop' page passes the `is_post_type_archive()` and `is_archive()` conditional checks, but not any check for post objects like `is_singular()` or `is_page()`, despite it being a regular `WP_Post` object.

On the other hand, currently AMT bases its logic on the WordPress conditional tags and, right now, the concept of a custom post type archive being mapped to a Page is not taken into account. I've already added a task to do some research about a generic (WooCommerce agnostic) way of detecting the situation.

I could certainly add a fix for WC specifically, but I'll try to avoid it, unless there is no other workaround.

Right now, AMT treats that page as an archive and generates metadata like it does for any other archive. Any custom information that has been in the Metadata metabox of that Page is not currently used.

If you would like to customize the generated metadata, please let me know about the specific parts that need customization and I'll try to give examples about how to do it. At this point, this is the best I can do.

However, please note that when this page is set as the front page, it can then be detected by AMT and the correct post object can be passed to the metadata generators. In other words, if the 'shop' page is set as the front page, the plugin is able to treat it like a post object rather than an archive, so everything is working fine in that case (since 2.10.10). This happens that in case of the front page the check is not based on `is_singular()` alone.

> I did however activate the WooCommerce option in your plugin's settings.

This option just attaches the WooCommerce specific metadata generators to the main metadata generators. Right now it has no effect on the shop page.

I'll re-open this issue and see if there is an easy way to resolve the problem with the rest of the metadata.

I hope all the above make sense. If you have any questions, please let me know.

George

**Comment by gnotaras** [comment]
BTW, here are some common modifications needed for archives, mainly the description, the image and custom full meta tags. Hope this is helpful

The following modify the description and the image of the archive of the custom post type `product`.

```php
// Shop description
function amt_wc_shop_custom_description( $default ) {
    return 'My custom shop description!';
}
add_filter('amt_generic_description_posttype_product_archive', 'amt_wc_shop_custom_description');

// Shop image
function amt_wc_shop_custom_image_url( $default ) {
    // Return:
    // - URL
    // - URL,WIDTHxHEIGHT notation
    // - ID of an image attachment
    return 'http://example.com/images/shop-logo.png,1200x800';
}
add_filter('amt_posttype_image_url_product', 'amt_wc_shop_custom_image_url');

// Shop full meta tags
function amt_wc_shop_custom_full_meta_tags( $default ) {
    if ( is_post_type_archive('product') ) {
        return '
<meta name="robots" content="noimageindex,noarchive" />
<link rel="alternate" hreflang="de" href="http://example.com/de/shop/" />
<link rel="alternate" hreflang="es" href="http://example.com/es/shop/" />
<meta property="myproperty1" content="value1" />
<meta property="myproperty2" content="value2" />';
    }
    return $default;
}
add_filter('amt_full_metatags_site', 'amt_wc_shop_custom_full_meta_tags');
```

The only way to customize archives with AMT is programmatically for maximum flexibility. Please let me know about any other customization that might be needed.

George

**Comment by gnotaras** [comment]
I think I have an idea about how I could add generic support for pages, to which an archive has been mapped, without using any 3rd party plugin conditional functions inside the metadata generators. I'll try to experiment a little at some later time and reply back.

**Comment by its-thomas** [comment]
I just noticed the following issue:
AMT seems to grab parts of the StatCounter Code (which I inserted on a page and which is not visible in the graphical wordpress editor, see http://statcounter.com/support/knowledge-base/14/) into the metatag:

`<meta property="og:description" content="Zum Reinschnuppern in unsere Rezeptsammlung - gratis! Download: Rezeptsammlung_Leseprobe.pdf var sc_project=123456789; var sc_invisible=1; var sc_security=123456789; var scJsHost = ((https: == document.location.protocol) ? https://secure. : http://www.); document." />`

Everything but 

> Zum Reinschnuppern in unsere Rezeptsammlung - gratis! Download: Rezeptsammlung_Leseprobe.pdf

 should NOT appear in the metatag.

**Comment by gnotaras** [comment]
Hi Thomas,

This is strange. The content passes through the [wp_kses()](https://codex.wordpress.org/Function_Reference/wp_kses) function with no allowed HTML tags, so the `<script>` tags should have been removed before a description was generated.

I'll try to look into this ASAP and reply back. Thanks for pointing it out

Btw, can you please open a new issue for this? For organizational purposes it is always very helpful to have each problem isolated in its own ticket. Thanks in advance. :-)

**Comment by gnotaras** [comment]
After doing some more research about this, I come to the conclusion that for the time being it is a wise idea to not incorporate any code that adds custom versions of the `is_singular()`, `is_page()` and `is_post_type_archive()` conditional tags, which are required in order to properly detect pages that act as archives. As far as I can tell, such a mapping does not seem to be standard practice, so I'm very hesitant about supporting it at this point.

So, I will now close this topic in this issue tracker. However, I'll keep the task about further research open in my internal bug tracker and make sure I find more info about how such cases should be dealt with.

Thank you for all your feedback. It is much appreciated! :-)

Best Regards,
George
