### ISSUE TITLE
import existing tags

### ISSUE THREAD

**Issue by janne45** [gnotaras/wordpress-add-meta-tags#6]
Is there a way to import existing title and description tags (from another plugin) captured by https://wordpress.org/plugins/seo-data-transporter/?
janne

**Comment by gnotaras** [comment]
Hello,

There are a few ways to do this:

* Use the aforementioned plugin to transfer data. However, this plugin requires some manual code changes in order to work correctly with Add-Meta-Tags. I had sent a patch to the developer, but it seems no new release has been made so far. In [this post](https://wordpress.org/support/topic/add-meta-tags-not-finding-any-records?replies=6#post-6408619) I have documented the changes that you need to make to the seo data transporter plugin. After this is done, it can detect the proper fields. This method makes changes to the database. Basically it just renames the relevant Custom Fields used by each plugin and is generally considered safe.

* Add-Meta-Tags supports reading data from other plugins. I've added this info in a page about [migrating from other plugins](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Migrate_to_Add-Meta-Tags) in the documentation on the project's wiki. This method does not make any changes to the database and is the safest of all, but requires 1) knowledge of the names of the Custom Fields that are used by your current seo plugin and, also, 2) the addition of some PHP code in the `functions.php` file of the theme (or in a custom plugin).

* A 3rd alternative is to manually rename the field names in the database by running SQL queries on the MySQL shell. This is not recommended if you are not familiar with this shell or with SQL. Check the [field names](http://www.codetrax.org/projects/wp-add-meta-tags/wiki/Data_Storage#Custom-Fields) used by Add-Meta-Tags to store data. This is the least recommended method.

In any case, if you need any help, feel free to ask.

Kind Regards,
George

**Comment by janne45** [comment]
Many thanks for fast response. A completely different thing - do you do web dev projects and if yes, would you be interested in looking at a brief and present a quote? 
Best regards,
janne

**Comment by gnotaras** [comment]
Hi Janne,

> do you do web dev projects

Unfortunately, currently there is no free time, so this is not possible. However, if you need anything related to Add-Meta-Tags, please feel free to ask.

George

**Comment by gnotaras** [comment]
Hi Janne, I will now close this issue. Thanks for your feedback.

**Comment by janne45** [comment]
OK, thanks for your help/janne

George Notaras wrote:
