### ISSUE TITLE
Bug #1510 is back ~ array_key_exists() expects parameter 2 to be array, boolean given

### ISSUE THREAD

**Issue by mchameddie** [gnotaras/wordpress-add-meta-tags#7]
Hello,

I installed the Add Meta Tags plugin today on a multisite WP instance. All but two of the sites have the following error message:

    Warning: array_key_exists() expects parameter 2 to be array, boolean given in /var/www/virtual/software.sil.org/htdocs/wp/wp-content/plugins/add-meta-tags/amt-utils.php on line 2526
    Warning: array_key_exists() expects parameter 2 to be array, boolean given in /var/www/virtual/software.sil.org/htdocs/wp/wp-content/plugins/add-meta-tags/amt-utils.php on line 2631

From reviewing the original issue thread, it sounded like you inserted a test *is_array($option)*, which I found in Line 864 of **amt-utils.php**. Unfortunately, the error message persists. I'm not sure why two of the sites do not produce this. They all use the exact same theme and were cloned off a template.

The version downloaded and installed is 2.9.4; however, I've network deactivated the plugin pending a resolution. Did I miss a step while installing or reviewing the original issue thread, or could this be a regression?

Thanks, Eddie

**Comment by gnotaras** [comment]
Hi Eddie,

I'll investigate this ASAP.

George

**Comment by gnotaras** [comment]
> I'm not sure why two of the sites do not produce this.

This happens because they have probably saved the settings from the admin panel.

BTW, the plugin auto upgrades the settings when new settings are added, so such a problem should not exist. But, in case of network sites there might be an issue with this 'settings auto-upgrade' feature. Perhaps there is an extra WordPress action-hook which should be used in case of network sites.

**Comment by gnotaras** [comment]
As a temporary workaround you could try manually uncommenting line *247* in the file `amt-settings.php` on line *247*:

Replace the line:

`
//add_action('plugins_loaded', 'amt_plugin_upgrade');
`

with:

`
add_action('plugins_loaded', 'amt_plugin_upgrade');
`

What this does is that it enables the old check whether the settings need upgrading or not. It should not affect performance or affect anything else.

If this resolved the issue, this will be come a permanent change in upcoming releases.

I'd appreciate it if you let me know if this does the trick. Thanks in advance.

George

**Comment by gnotaras** [comment]
I should note that adding the `is_array()` check in every data retrieval from the `$options` array is not really the solution as it adds unnecessary complexity to the code. The solution is to have the options be properly upgraded. Apparently the change of the place where the upgrade function is called has caused some problems.

**Comment by mchameddie** [comment]
Thank you, George. I will try the workaround by Monday at the latest.

~ Eddie

Eddie McHam

**Comment by gnotaras** [comment]
Eddie, I think I've made up my mind about this. I'll revert back to the original "settings upgrade" check as described above. According to my tests, there is absolutely no performance impact by doing it on every load instead of doing it only when the admin interface is loaded. This check only compares a number in the settings array, which BTW has already been cached by wordpress.

The `is_array()` and `array_key_exists()` checks that have been added so far in order to resolve issues similar to this one will be removed over time. I wouldn't like to make a lot of changes at once so right now I'm going to leave them in the code.

Possibly I'll release a new version within the weekend. Whenever you try it, I'd appreciate some feedback about whether it resolves the problem or not.

Thanks for reporting this issue and also I'm sorry for any inconvenience this has caused.

George

**Comment by gnotaras** [comment]
Eddie, I've incorporated the aforementioned change in the new 2.9.5 release. The issue should be fixed. Please let me know if you notice any problems whenever you test the new release.

Now I'm going to mark this issue as closed. Feel free to add your feedback.

**Comment by mchameddie** [comment]
Good morning George,

Just letting you know the error messages are gone. Thanks so much for your prompt assistance with this.  :)

~ Eddie

**Comment by gnotaras** [comment]
Thanks for letting me know! :)
