### ISSUE TITLE
Remove HTML comments?

### ISSUE THREAD

**Issue by catchmyfame** [gnotaras/wordpress-add-meta-tags#8]
Is there an option to remove the `<!-- BEGIN Metadata added by Add-Meta-Tags WordPress plugin -->` and `<!-- END Metadata added by Add-Meta-Tags WordPress plugin -->` comments that the plugin adds?

**Comment by gnotaras** [comment]
Hello,

No such option or filter based on/off switch exists and there are no plans to add one in the foreseeable future. Removing the comments requires editing of the core plugin files.

This plugin is a free product with full functionality and, also, the resources in order to market/promote it are extremely limited. Besides, the comments serve as a way to identify the plugin output within the HTML source and such practice is common among many wordpress plugins.

I think the above comment is very simple and serves its purpose in an uninstrusive way, so it should not be a problem for any web site. However, I'd be very interested in knowing why this is a problem for your project.

Kind Regards,
George

PS: Now that I see it, I think there is a mistake, a missing 'the', which will be fixed in future releases.

**Comment by catchmyfame** [comment]
Never said it was a problem, just wanted to know if there was a way to remove it without hacking the plugin's files. My main concern is that for users that try and hide every mention that their site runs WordPress, that this plugin announces it which some might see as a security issue. Maybe changing the comments to `<!-- BEGIN Metadata added by Add-Meta-Tags plugin -->` instead? Great plugin BTW.

**Comment by gnotaras** [comment]
> My main concern is that for users that try and hide every mention that their site runs WordPress [...]

I see. This is the only case that I could consider a valid reason, but, as long as the application/plugins/themes source code and media files are accessible over the internet, it's really difficult to hide the fact that you are running wordpress. Moreover, the default `wp-{admin,content,includes}` directory structures, the default login/registration pages, the default archive types and permalink structures would make it even more difficult to the point that modifying the above comment would only be a tiny fraction of the huge amount of manual work that would have to be done.

But, still, this is a legit reason, so I'll possibly add a filter hook to be used as an on/off switch or limiter of the information that becomes available through that comment.

Thanks for your feedback,

George

**Comment by gnotaras** [comment]
My thoughts are to add a filter based switch which would accepts the following strings:

 * `full` -> Metadata added by the Add-Meta-Tags plugin (v1.2.3) for WordPress
 * `prod` (the default) -> Metadata added by the Add-Meta-Tags plugin for WordPress
 * `min` -> Metadata added by the Add-Meta-Tags plugin

That's the best I can do about it. I hope this is fine.

George

**Comment by catchmyfame** [comment]
Look great, thanks.

**Comment by gnotaras** [comment]
Hi, I'm sorry for the delay. I gave this a second thought. I plan to add an option to remove the HTML comments in the next release.

**Comment by gnotaras** [comment]
Hi, 2.10.6 will have an option to remove the HTML comments. The accompanying text contains a notice about donations when this is used. Please feel free to use it on your sites without donating. Thanks for your feedback.

I'll now close this ticket.

George
